apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vml-base

resources:
  - vml-api-deployment.yaml
  - vml-api-service.yaml
  - vml-api-pvc.yaml
  - tracking-api-deployment.yaml
  - tracking-api-service.yaml

commonLabels:
  component: api
  part-of: vietmap-live

namespace: vietmap-live

