apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vml-api-pvc
  labels:
    app: vml-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath