apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vietmap-live-dev
  namespace: vml-argo
  labels:
    app.kubernetes.io/name: vietmap-live-dev-project
spec:
  description: Vietmap Live Dev project
  
  # Source repositories
  sourceRepos:
  - 'https://github.com/trongtqFX21166/vml_argocd.git'
  
  # Destinations
  destinations:
  - namespace: vietmap-live-dev
    server: https://kubernetes.default.svc
  
  # Allowed cluster resources
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  
  # Allowed namespace resources
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: ''
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment
  - group: apps
    kind: ReplicaSet
  - group: networking.k8s.io
    kind: Ingress
  
  # Simple RBAC
  roles:
  - name: developer
    description: Developer access to vml project
    policies:
    - p, proj:vietmap-live-dev:developer, applications, get, vietmap-live-dev/*, allow
    - p, proj:vietmap-live-dev:developer, applications, sync, vietmap-live-dev/*, allow
    groups:
    - vietmap-live-dev:developers