apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vml-api-test

resources:
  - vml-api-deployment.yaml
  - vml-api-service.yaml
  - vml-api-pvc.yaml
  - vml-api-pv.yaml

commonLabels:
  component: api
  part-of: vietmap-live
  service: vml-api-test

namespace: vietmap-live-dev