apiVersion: apps/v1
kind: Deployment
metadata:
  name: vml-api-test
  labels:
    app: vml-api-test
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: vml-api-test
  template:
    metadata:
      labels:
        app: vml-api-test
    spec:
      containers:
        - name: vml-api-test
          image: vmapi/vml-s2:vietmapcloud.vietmaplive.api.1.0.10
          ports:
            - name: api
              containerPort: 6078
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Dev"
            - name: ASPNETCORE_URLS
              value: "http://+:6078"
            - name: TZ
              value: "Asia/Bangkok"
            - name: IsShowOtpV1
              value: "true"
          # Resources - Increased memory limits
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          # Volume mount
          volumeMounts:
            - name: vml-logs
              mountPath: /app/logs
              subPath: vml-api-test-logs
      volumes:
        - name: vml-logs
          persistentVolumeClaim:
            claimName: vml-api-test-pvc
      # Add image pull secret
      imagePullSecrets:
        - name: registry-secret-clound
      # Security
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
