apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vml-api-test-pvc
  labels:
    app: vml-api-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage