apiVersion: v1
kind: PersistentVolume
metadata:
  name: vml-api-test-pv
  namespace: vietmap-live-dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /home/admin/vml-api-test-pv
    type: DirectoryOrCreate  # This automatically creates the directory    
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: DoesNotExist    