apiVersion: v1
kind: Service
metadata:
  name: tracking-api-test
  labels:
    app: tracking-api-test
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 80
    targetPort: 6002
    protocol: TCP
  selector:
    app: tracking-api-test